### ISSUE TITLE
live_server unable to serve static files under Django 1.8.7

### ISSUE THREAD

**Issue by bobsilverberg** [pytest-dev/pytest-django#294]
I've been trying to get a test running using selenium and the `live_server` fixture, and I couldn't seem to get the server to serve up static files. I compared the code in `LiveServerHelper.__init__` [1] to the code for `LiveServerTestCase` in Django [2] and it looked like the problem was with the StaticFilesHandler that was being passed in to `LiveServerThread`.

I changed the code locally to remove the path that is specific to Django >= 1.7 [3] and that seems to have solved the problem for me.

Is this in fact a bug, or am I just doing something wrong?

[1] https://github.com/pytest-dev/pytest-django/blob/master/pytest_django/live_server_helper.py#L14
[2] https://github.com/django/django/blob/stable/1.8.x/django/test/testcases.py#L1214
[3] https://github.com/pytest-dev/pytest-django/blob/master/pytest_django/live_server_helper.py#L29-L35

**Comment by pelme** [comment]
@bobsilverberg Do you have `django.contrib.staticfiles` in INSTALLED_APPS?

The idea is that you should get static files with the `live_server` fixture automatically, as long as staticfiles is installed.

**Comment by bobsilverberg** [comment]
@pelme Yes, I do have `django.contrib.staticfiles` in `INSTALLED_APPS`, and with the current code it won't serve static files for me. It only works if I comment out that code path and allow it to use `_StaticFilesHandler` from `django.test.testcases` instead. I assume the current code has been tested with Django 1.8.7? What is that other code path supposed to buy me?

**Comment by bobsilverberg** [comment]
FTR, a colleague of mine was able to reproduce the same results with my codebase.

**Comment by pelme** [comment]
The idea is that you should be able to use the `live_server` fixture and have static files just work. With standard Django testcases you have to specifically subclass from `django.contrib.staticfiles.StaticLiveServerTestCase` if you use staticfiles and not want to run collectstatic manually. We look in INSTALLED_APPS and enable static files for live_server.

The relevant discussion (which is a bit verbose) for this can be found in issue #120 and PR #140 . There is a test case that verifies that this should be working:

https://github.com/pytest-dev/pytest-django/blob/d28ecf2e48cb3f58509e5f4a8ea81a75ac6c3872/tests/test_fixtures.py#L148-L187

I created an empty project on my computer and got working, both with Django 1.8.7 and 1.9 and got it working. Can you please try to create a minimal project and try to reproduce your problem in it?

```
~ → vf tmp
New python executable in /Users/andreas/.virtualenvs/tempenv-042557997b82/bin/python
Installing setuptools, pip...done.
‹tempenv-042557997b82› ~ → pip install django==1.8.7 pytest-django requests
Downloading/unpacking django==1.8.7
  Downloading Django-1.8.7-py2.py3-none-any.whl (6.2MB): 6.2MB downloaded
Downloading/unpacking pytest-django
  Downloading pytest_django-2.9.1-py2.py3-none-any.whl
Downloading/unpacking requests
  Downloading requests-2.8.1-py2.py3-none-any.whl (497kB): 497kB downloaded
Downloading/unpacking pytest>=2.5 (from pytest-django)
  Downloading pytest-2.8.3-py2.py3-none-any.whl (149kB): 149kB downloaded
Downloading/unpacking py>=1.4.29 (from pytest>=2.5->pytest-django)
  Downloading py-1.4.31-py2.py3-none-any.whl (81kB): 81kB downloaded
Installing collected packages: django, pytest-django, requests, pytest, py
Successfully installed django pytest-django requests pytest py
Cleaning up...
‹tempenv-042557997b82› ~ → django-admin startproject issue294project
‹tempenv-042557997b82› ~ → cd issue294project
‹tempenv-042557997b82› ~/issue294project → ./manage.py startapp issue294app
‹tempenv-042557997b82› ~/issue294project → mkdir issue294app/static
‹tempenv-042557997b82› ~/issue294project → echo some content > issue294app/static/foo.txt
‹tempenv-042557997b82› ~/issue294project → vi issue294app/test_staticfiles.py
‹tempenv-042557997b82› ~/issue294project → cat issue294app/test_staticfiles.py
import requests
def test_staticfiles(live_server):
    response = requests.get(live_server + '/static/foo.txt')
    assert 'some content' in response.content
‹tempenv-042557997b82› ~/issue294project → vi issue294project/settings.py  # add issue294app to INSTALLED_APPS
‹tempenv-042557997b82› ~/issue294project → py.test --ds=issue294project.settings -vv
================================================= test session starts ==================================================
platform darwin -- Python 2.7.10, pytest-2.8.3, py-1.4.31, pluggy-0.3.1 -- /Users/andreas/.virtualenvs/tempenv-042557997b82/bin/python
cachedir: .cache
django settings: issue294project.settings (from command line option)
rootdir: /Users/andreas/issue294project, inifile:
plugins: django-2.9.1
collected 1 items

issue294app/test_staticfiles.py::test_staticfiles PASSED

=============================================== 1 passed in 0.87 seconds ===============================================
‹tempenv-042557997b82› ~/issue294project →
```

**Comment by bobsilverberg** [comment]
Thanks for the detailed response @pelme. I figured out what my issue is, but I think it is still an issue for `pytest-django`. The problem is that I am using `django-pipeline` for my static assets, so the line in my template that generates the css link, for example is:

`{% stylesheet 'base' %}`

This generates the following in the html that is delivered to the browser:

`<link type="text/css" rel="stylesheet" href="/static/css/base.min.ad332ce234b5.css" />`

That file does not exist in my application folder, it is only generated when calling `collectstatic` and is only available from the actual `/static` folder.

The problem is that, when using `django.contrib.staticfiles.StaticLiveServerTestCase` it tries to find the file in the application folder and fails. I tested this by generating the file and then temporarily copying it into the application folder and then it is found. So what you say above makes sense, that if you want to be able to run the liveserver without having to run `collectstatic` it all works. The problem is that I do want to run `collectstatic` because this is an end-to-end Selenium test and I want to test the full pipeline, not just what I would get if running with `debug=True`. I want my functional test to use conditions as close to production as possible, so I want to generate the batched and minified css and js files and then  run my tests using them.

Currently `pytest-django` seems to prevent me from doing that because of the code path that I have now commented out.

Perhaps there is another way of telling `pytest-django` that I do not want it to use `django.contrib.staticfiles.handlers.StaticFilesHandler`, and if so that would solve my problem. But if such a mechanism does not exist I am stuck with my current hack which is to use my own fork of `pytest-django` with that code removed.

Do you have any suggestions on how to better deal with this?

**Comment by pelme** [comment]
Could you put `'pipeline.finders.PipelineFinder'` in STATICFILES_FINDERS?

If you want true end-to-end tests with your static files collected exactly as in production, I'd recommend running gunicorn (or your app server) in a subprocess.

I currently use live_server myself, but like to switch to just start gunicorn for the my own Selenium/end-to-end tests. For comparison I used to start a celery worker in a thread from tests, now I just launch a subprocess with a celery worker by just running the celery program. It is more reliable and it is closer to the production environment. End-to-end tests should really just start processes and not run any part of the actual system in the same process. It can lead to surprising effects.

**Comment by pelme** [comment]
Did you try putting `'pipeline.finders.PipelineFinder'` in STATICFILES_FINDERS?

I think that django-pipeline should integrate properly with staticfiles without having to run collectstatic (How would runserver work otherwise? You should not need to run collectstatic just to have it work, right?) 

I'm closing this issue for now since it is so old without any follow ups, feel free to reopen it again if this issue still persists!

**Comment by rightx2** [comment]
Still have problem even I put 'pipeline.finders.PipelineFinder' in STATICFILES_FINDERS..

**Comment by samamorgan** [comment]
I'm having what seems like the same issue as is described here. Been tearing my hair out pouring over settings and our various apps related to static files, but this thread is the first real progress.

I've been trying to convert our tests over to pytest using this and `pytest-playwright` for end-to-end tests, and our Vite compiled assets were never available. Commenting out the code as @bobsilverberg noted solves the issue for me. We were inheriting from `LiveServerTestCase` previously, which only uses `_StaticFilesHandler`.

I'm not sure where to go from here. I really don't want to migrate back to using the `LiveServerTestCase` class, but as things stand I can't make Playwright tests work.

**Comment by trey** [comment]
I found a workaround that'll do the trick for me, I think. Making sure to run `collectstatic` before running tests and overriding settings by loading a new settings file that inherits from the default one (I'm generally not a fan of this method (preferring environment variables), but I think I'm ok with it in this case.

`pyproject.toml`:

```toml
[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "your_project.settings_playwright"
# …
```

`settings_playwright.py`:

```python
# flake8: noqa
from .settings import *

INSTALLED_APPS.remove("django.contrib.staticfiles")
```

Hope that helps someone else!
